/**
 * Embeds src/views/index.html into a TypeScript module so the page needs
 * no filesystem access at runtime — serverless platforms (Vercel) ship a
 * read-only bundle where a path-based readFileSync can't be traced, and
 * would fail with ENOENT on the first request.
 *
 * Run automatically by `bun run build` and `bun run dev`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'src', 'views', 'index.html');
const target = path.join(root, 'src', 'views', 'indexHtml.ts');

const html = fs.readFileSync(source, 'utf8');
const escaped = html
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

const out = [
  '/** AUTO-GENERATED by scripts/embed-view.ts — edit src/views/index.html instead. */',
  'export const HOME_HTML = `' + escaped + '`;',
  '',
].join('\n');

fs.writeFileSync(target, out);
console.log(`embedded ${path.relative(root, source)} -> ${path.relative(root, target)} (${html.length} bytes)`);
